services: 
 # web app:
 web-app:
   container_name: web-app
   build: ./app
   security_opt:
     - no-new-privileges:true
   restart: always
   ports:
     - 80:80
   env_file:
     - ./app/.env
   networks:
     - my-network

networks:
  my-network:
    driver: bridge