services: 
 # front-end:
 front:
   container_name: front
   build: ./app
   security_opt:
     - no-new-privileges:true
   restart: always
   ports:
     - 80:80
   env_file:
     - ./app/.env
   networks:
    - backend_network